version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Monte le fichier SQLite dans le conteneur
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  sqlite_data:
