# Generated by Django 5.1.4 on 2025-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingtip_delete_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtip',
            name='content',
        ),
        migrations.AddField(
            model_name='trainingtip',
            name='description',
            field=models.TextField(default='Pas de description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trainingtip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='trainingtip',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
