# Generated by Django 5.1.4 on 2025-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_trainingtip_content_trainingtip_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtip',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur'), ('guest', 'Invité')], default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingtip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingtip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trainingtip',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingtip',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
